# Generated by Django 4.0.4 on 2023-04-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
