# Generated by Django 4.1.8 on 2023-04-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_view_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission_distance_free_interference', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission_distance_interference', models.CharField(blank=True, max_length=50, null=True)),
                ('max_download_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('lowest_latency', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'videotransmission',
            },
        ),
        migrations.RemoveField(
            model_name='drone',
            name='carrying_capacity',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='flight_time',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='max_speed',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='model_version',
        ),
        migrations.AddField(
            model_name='drone',
            name='ascent_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='descent_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='gps_system',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='horizontal_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='internal_storage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='max_flight_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='operating_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='takeoff_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensors_type', models.CharField(blank=True, max_length=100, null=True)),
                ('forward', models.CharField(blank=True, max_length=100, null=True)),
                ('backward', models.CharField(blank=True, max_length=100, null=True)),
                ('lateral', models.CharField(blank=True, max_length=100, null=True)),
                ('upward', models.CharField(blank=True, max_length=100, null=True)),
                ('downward', models.CharField(blank=True, max_length=100, null=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone.drone')),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='RemoteController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_operating_time', models.FloatField(blank=True, null=True)),
                ('max_supported_mobile_device_size', models.CharField(blank=True, max_length=50)),
                ('transmitter_power', models.FloatField(blank=True, null=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone.drone')),
            ],
            options={
                'db_table': 'remotecontroller',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_sensor', models.CharField(blank=True, max_length=100, null=True)),
                ('lens', models.CharField(blank=True, max_length=100, null=True)),
                ('iso_range', models.CharField(blank=True, max_length=50, null=True)),
                ('shutter_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('max_image_size', models.CharField(blank=True, max_length=50, null=True)),
                ('photography_modes', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_format', models.CharField(blank=True, max_length=50, null=True)),
                ('video_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('video_format', models.CharField(blank=True, max_length=50, null=True)),
                ('max_video_bitrate', models.CharField(blank=True, max_length=50, null=True)),
                ('digital_zoom', models.CharField(blank=True, max_length=50, null=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone.drone')),
            ],
            options={
                'db_table': 'camera',
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('battery_type', models.CharField(blank=True, max_length=50, null=True)),
                ('charging_temperature', models.IntegerField(blank=True, null=True)),
                ('charging_time', models.FloatField()),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drone.drone')),
            ],
            options={
                'db_table': 'battery',
            },
        ),
    ]
