# Generated by Django 4.0.4 on 2023-04-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='image',
            field=models.ImageField(default=0, upload_to='images/drones/'),
            preserve_default=False,
        ),
    ]
