# Generated by Django 4.1.8 on 2023-04-28 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0002_videotransmission_remove_drone_carrying_capacity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensor',
        ),
    ]
