# Generated by Django 4.1.8 on 2023-04-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0003_rename_sensors_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='operating_temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
