# Generated by Django 4.1.8 on 2023-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0004_alter_drone_operating_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='charging_temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
