# Generated by Django 4.1.8 on 2023-04-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0005_alter_battery_charging_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='image_sensor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='iso_range',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='lens',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='photography_modes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='video_resolution',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
