# Generated by Django 4.1.8 on 2023-04-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0006_alter_camera_image_sensor_alter_camera_iso_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='iso_range',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='lens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='photography_modes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='video_resolution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
