# Generated by Django 4.1.8 on 2023-04-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0007_alter_camera_iso_range_alter_camera_lens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecontroller',
            name='max_operating_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='remotecontroller',
            name='transmitter_power',
            field=models.TextField(blank=True, null=True),
        ),
    ]
