# Generated by Django 4.1.8 on 2023-04-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0008_alter_remotecontroller_max_operating_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='backward',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='downward',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='forward',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='lateral',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='upward',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
