# Generated by Django 4.1.8 on 2023-04-28 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0009_alter_sensor_backward_alter_sensor_downward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotransmission',
            name='drone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drone.drone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='backward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='downward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='forward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='lateral',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='upward',
            field=models.TextField(blank=True, null=True),
        ),
    ]
