# Generated by Django 4.1.8 on 2023-04-28 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0010_videotransmission_drone_alter_sensor_backward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battery', to='drone.drone'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='drone.drone'),
        ),
        migrations.AlterField(
            model_name='drone',
            name='takeoff_altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remotecontroller',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller', to='drone.drone'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to='drone.drone'),
        ),
        migrations.AlterField(
            model_name='videotransmission',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmission', to='drone.drone'),
        ),
        migrations.AlterField(
            model_name='videotransmission',
            name='operating_frequency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videotransmission',
            name='transmission_distance_free_interference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videotransmission',
            name='transmission_distance_interference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
